package org.trostheide.gantry.app.gui;

import org.commonmark.ext.gfm.tables.TablesExtension;
import org.commonmark.node.Heading;
import org.commonmark.node.Node;
import org.commonmark.node.Text;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import java.awt.*;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Renders {@code docs/USER_GUIDE.md} in-app as a formatted, navigable document, instead of
 * shelling out to whatever the OS associates with {@code .md} files. The markdown is rendered
 * once to HTML (via commonmark) and shown in a {@link JEditorPane}, with a clickable table of
 * contents (built from the document's headings) down the left side and an "open externally" link
 * for anyone who wants the syntax-highlighted GitHub rendering instead.
 *
 * <p>Heading anchors are generated by {@link #assignAnchorIds}, which walks the parsed AST once
 * and hands out slug ids in document order (deduping repeats with a numeric suffix, same scheme
 * GitHub uses); those same ids back both the table-of-contents links and the {@code id="..."}
 * attributes the HTML renderer emits, so a TOC click and the resulting in-page anchor always agree.
 */
final class HelpDialog extends JDialog {

    private static final String RESOURCE_PATH = "/docs/USER_GUIDE.md";
    private static final String FALLBACK_FILE = "docs/USER_GUIDE.md";

    /** One entry per heading, in document order, for the table-of-contents list. */
    private record TocEntry(String title, String anchorId, int level) {
        @Override public String toString() {
            return "  ".repeat(Math.max(0, level - 1)) + title;
        }
    }

    HelpDialog(Window owner) {
        super(owner, "Gantry User Guide", ModalityType.MODELESS);

        List<org.commonmark.Extension> extensions = List.of(TablesExtension.create());
        String markdown = loadMarkdown();
        Node document = Parser.builder().extensions(extensions).build().parse(markdown);
        List<TocEntry> toc = new ArrayList<>();
        Map<Heading, String> anchorIds = assignAnchorIds(document, toc);

        String html = HtmlRenderer.builder()
                .extensions(extensions)
                .attributeProviderFactory(context -> (node, tagName, attributes) -> {
                    if (node instanceof Heading heading) {
                        String id = anchorIds.get(heading);
                        if (id != null) {
                            attributes.put("id", id);
                        }
                    }
                })
                .build()
                .render(document);

        JEditorPane editorPane = new JEditorPane();
        editorPane.setEditable(false);
        editorPane.setEditorKit(styledEditorKit());
        // Fill the whole viewport white so the light page doesn't sit on a dark-theme background.
        editorPane.setBackground(Color.WHITE);
        editorPane.setText(wrapHtml(html));
        editorPane.setCaretPosition(0);
        editorPane.addHyperlinkListener(this::onHyperlink);

        JScrollPane contentScroll = new JScrollPane(editorPane);
        contentScroll.getVerticalScrollBar().setUnitIncrement(16);

        JList<TocEntry> tocList = new JList<>(toc.toArray(new TocEntry[0]));
        tocList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tocList.addListSelectionListener(e -> {
            TocEntry selected = tocList.getSelectedValue();
            if (selected != null) {
                scrollToAnchor(editorPane, selected.anchorId());
            }
        });
        JScrollPane tocScroll = new JScrollPane(tocList);
        tocScroll.setPreferredSize(new Dimension(220, 0));
        tocScroll.setBorder(BorderFactory.createTitledBorder("Contents"));

        JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, tocScroll, contentScroll);
        split.setDividerLocation(220);
        split.setResizeWeight(0.0);

        JButton openExternalBtn = new JButton("Open in browser/editor");
        openExternalBtn.setToolTipText("Open docs/USER_GUIDE.md externally (e.g. to see it rendered on GitHub).");
        openExternalBtn.addActionListener(e -> openExternally());
        JButton closeBtn = new JButton("Close");
        closeBtn.addActionListener(e -> dispose());
        JPanel buttons = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttons.add(openExternalBtn);
        buttons.add(closeBtn);

        setLayout(new BorderLayout());
        add(split, BorderLayout.CENTER);
        add(buttons, BorderLayout.SOUTH);
        getRootPane().setDefaultButton(closeBtn);

        setSize(960, 720);
        setLocationRelativeTo(owner);
    }

    /**
     * Scrolls to the heading with the given anchor id. {@link JEditorPane#scrollToReference}
     * only matches {@code <a name="...">} tags, not arbitrary {@code id} attributes, so it
     * never finds our commonmark-generated heading ids; this looks the element up directly via
     * {@link HTMLDocument#getElement(String)} and scrolls to its on-screen position instead.
     */
    private static void scrollToAnchor(JEditorPane editorPane, String anchorId) {
        if (!(editorPane.getDocument() instanceof HTMLDocument doc)) {
            return;
        }
        Element element = doc.getElement(anchorId);
        if (element == null) {
            return;
        }
        try {
            Rectangle r = editorPane.modelToView(element.getStartOffset());
            if (r != null) {
                r.height = editorPane.getVisibleRect().height;
                editorPane.scrollRectToVisible(r);
                editorPane.setCaretPosition(element.getStartOffset());
            }
        } catch (BadLocationException ignored) {
            // nothing sensible to scroll to
        }
    }

    private void onHyperlink(HyperlinkEvent e) {
        if (e.getEventType() != HyperlinkEvent.EventType.ACTIVATED) {
            return;
        }
        String href = e.getDescription();
        if (href == null) {
            return;
        }
        if (href.startsWith("#")) {
            ((JEditorPane) e.getSource()).scrollToReference(href.substring(1));
            return;
        }
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(URI.create(href));
            }
        } catch (IOException | IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Couldn't open link: " + href, "Link", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void openExternally() {
        Path file = Path.of(FALLBACK_FILE);
        if (!Files.exists(file)) {
            JOptionPane.showMessageDialog(this, "User guide not found at " + FALLBACK_FILE + ".",
                    "User Guide", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.OPEN)) {
                Desktop.getDesktop().open(file.toFile());
                return;
            }
        } catch (IOException ignored) {
            // fall through to the path message below
        }
        JOptionPane.showMessageDialog(this, "See " + file.toAbsolutePath(), "User Guide",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /** Reads the bundled copy first (works from the packaged jar); falls back to the source tree. */
    private static String loadMarkdown() {
        try (InputStream in = HelpDialog.class.getResourceAsStream(RESOURCE_PATH)) {
            if (in != null) {
                return new String(in.readAllBytes(), StandardCharsets.UTF_8);
            }
        } catch (IOException ignored) {
            // fall through to the file-system fallback below
        }
        try {
            return Files.readString(Path.of(FALLBACK_FILE), StandardCharsets.UTF_8);
        } catch (IOException ex) {
            return "# User Guide not found\n\nCouldn't find `" + RESOURCE_PATH + "` on the classpath or `"
                    + FALLBACK_FILE + "` on disk.";
        }
    }

    /**
     * Walks every H1-H3 heading in document order and assigns it a GitHub-style slug id
     * (lowercase, non-alphanumerics turned into hyphens, duplicates suffixed {@code -1}, {@code
     * -2}, ...). Returns a node-identity map so the same id can be reused both for the
     * table-of-contents link and the {@code id} attribute the HTML renderer emits for that node.
     */
    private static Map<Heading, String> assignAnchorIds(Node document, List<TocEntry> tocOut) {
        Map<Heading, String> ids = new HashMap<>();
        Set<String> used = new HashSet<>();
        assignAnchorIds(document.getFirstChild(), ids, used, tocOut);
        return ids;
    }

    private static void assignAnchorIds(Node node, Map<Heading, String> ids, Set<String> used,
            List<TocEntry> tocOut) {
        while (node != null) {
            if (node instanceof Heading heading && heading.getLevel() <= 3) {
                String text = headingText(heading);
                String id = uniqueSlug(text, used);
                ids.put(heading, id);
                tocOut.add(new TocEntry(text, id, heading.getLevel()));
            }
            assignAnchorIds(node.getFirstChild(), ids, used, tocOut);
            node = node.getNext();
        }
    }

    private static String uniqueSlug(String text, Set<String> used) {
        String base = slugify(text);
        String candidate = base;
        int suffix = 1;
        while (!used.add(candidate)) {
            candidate = base + "-" + suffix++;
        }
        return candidate;
    }

    private static String slugify(String text) {
        String slug = text.toLowerCase()
                .replaceAll("[^a-z0-9\\s-]", "")
                .trim()
                .replaceAll("\\s+", "-");
        return slug.isEmpty() ? "section" : slug;
    }

    private static String headingText(Node node) {
        StringBuilder sb = new StringBuilder();
        for (Node child = node.getFirstChild(); child != null; child = child.getNext()) {
            if (child instanceof Text text) {
                sb.append(text.getLiteral());
            } else {
                sb.append(headingText(child));
            }
        }
        return sb.toString();
    }

    /** A reasonably readable CSS stylesheet for Swing's HTML 3.2-ish {@link HTMLEditorKit} renderer. */
    private static HTMLEditorKit styledEditorKit() {
        HTMLEditorKit kit = new HTMLEditorKit();
        StyleSheet css = kit.getStyleSheet();
        // Render as a self-contained light page (white background, dark text) rather than
        // inheriting the look-and-feel's colours: the rest of these rules assume a light page
        // (light code backgrounds, gray borders), and under a dark theme the inherited light
        // foreground would otherwise leave dark-theme text unreadable on those light backgrounds.
        css.addRule("body { font-family: sans-serif; font-size: 13pt; margin: 12px 18px;"
                + " color: #1a1a1a; background-color: #ffffff; }");
        css.addRule("h1 { font-size: 20pt; border-bottom: 1px solid #999; padding-bottom: 4px; }");
        css.addRule("h2 { font-size: 16pt; margin-top: 22px; border-bottom: 1px solid #ccc; padding-bottom: 2px; }");
        css.addRule("h3 { font-size: 14pt; margin-top: 16px; }");
        css.addRule("p { margin-top: 6px; margin-bottom: 6px; }");
        css.addRule("code { background-color: #eeeeee; font-family: monospace; padding: 1px 3px; }");
        css.addRule("pre { background-color: #f4f4f4; padding: 8px; border: 1px solid #ddd; }");
        css.addRule("blockquote { color: #555555; border-left: 3px solid #bbbbbb; padding-left: 10px; margin-left: 4px; }");
        css.addRule("table { border-collapse: collapse; margin: 8px 0; }");
        css.addRule("th, td { border: 1px solid #bbbbbb; padding: 4px 8px; }");
        css.addRule("th { background-color: #e8e8e8; }");
        css.addRule("a { color: #1a55c7; }");
        return kit;
    }

    private static String wrapHtml(String bodyHtml) {
        return "<html><head></head><body>" + bodyHtml + "</body></html>";
    }
}
